"""
VimMo Code Generator — emits VimScript from AST
"""

from ast_nodes import *
from typing import List, Optional


class CodegenError(Exception):
    pass


class Codegen:
    def __init__(self):
        self.indent_level = 0
        self.output: List[str] = []
        self._lambda_counter = 0
        self._job_counter = 0
        self._script_name = "vimmo"
        # const names for compile-time check
        self._consts: set = set()
        # class names known
        self._classes: set = set()
        # Scope management
        self.scope_stack: List[dict] = []  # {'kind': 'fn'|'lambda', 'params': set, 'funcref_vars': set}
        self.function_depth = 0
        self.script_vars: set = set()  # Variables defined at script scope (s:)
        self._script_funcref_vars: set = set()  # Funcref vars at script scope (need capitalization)
        self._imported_names: set = set()  # Names imported from other modules (global scope, no prefix)

    def enter_scope(self, kind: str, params: List[str]):
        self.scope_stack.append({"kind": kind, "params": set(params)})
        if kind == "fn":
            self.function_depth += 1

    def leave_scope(self):
        scope = self.scope_stack.pop()
        if scope["kind"] == "fn":
            self.function_depth -= 1

    def _register_funcref_var(self, name: str):
        """Mark a variable as holding a funcref (requires capital-first name in VimScript)."""
        if self.scope_stack:
            self.scope_stack[-1].setdefault("funcref_vars", set()).add(name)
        else:
            self._script_funcref_vars.add(name)

    def _is_funcref_var(self, name: str) -> bool:
        """Return True if name was registered as a funcref variable in any enclosing scope."""
        for scope in reversed(self.scope_stack):
            if name in scope.get("funcref_vars", set()):
                return True
        return name in self._script_funcref_vars

    def _cap_funcref_name(self, name: str) -> str:
        """Capitalize first letter if name is a registered funcref variable."""
        if self._is_funcref_var(name) and name and name[0].islower():
            return name[0].upper() + name[1:]
        return name

    def indent(self) -> str:
        return "  " * self.indent_level

    def emit(self, line: str = ""):
        self.output.append(self.indent() + line)

    def emit_raw(self, line: str):
        self.output.append(line)

    def generate(self, node: Program) -> str:
        self.emit('" Generated by VimMo transpiler')
        self.emit('" https://github.com/vimmo-lang/vimmo')
        self.emit("")
        self.emit("scriptencoding utf-8")
        self.emit("")
        for stmt in node.body:
            self.gen_stmt(stmt)
            self.emit("")
        return "\n".join(self.output)

    # ── Statements ────────────────────────────────────────────────────────────

    def gen_stmt(self, node: Node):
        if isinstance(node, VarDecl):
            self.gen_var_decl(node)
        elif isinstance(node, FnDecl):
            self.gen_fn_decl(node)
        elif isinstance(node, Return):
            self.gen_return(node)
        elif isinstance(node, If):
            self.gen_if(node)
        elif isinstance(node, For):
            self.gen_for(node)
        elif isinstance(node, While):
            self.gen_while(node)
        elif isinstance(node, Break):
            self.emit("break")
        elif isinstance(node, Continue):
            self.emit("continue")
        elif isinstance(node, Echo):
            self.emit(f"echo {self.gen_expr(node.value)}")
        elif isinstance(node, ExprStmt):
            expr = node.expr
            # Handle assignment expressions as statements
            if isinstance(expr, Assign):
                target = self.gen_expr(expr.target)
                val = self.gen_expr(expr.value)
                self.emit(f"let {target} = {val}")
                return
            if isinstance(expr, AugAssign):
                target = self.gen_expr(expr.target)
                val = self.gen_expr(expr.value)
                self.emit(f"let {target} {expr.op} {val}")
                return

            # Vim helpers that emit their own lines return ''
            if isinstance(expr, Call) and isinstance(expr.callee, Ident):
                name = expr.callee.name
                if name in ("autocmd", "command") or (
                    name == "map"
                    and len(expr.args) == 3
                    and isinstance(expr.args[0], StringLit)
                    and expr.args[0].value in ("n", "i", "v", "x", "o", "c", "t")
                ):
                    self.gen_call(expr)
                    return
            result = self.gen_expr(expr)
            if result:  # skip empty strings from helpers
                if self._is_call_expr(expr):
                    self.emit(f"call {result}")
                else:
                    self.emit(f"let l:_ = {result}")
        elif isinstance(node, Import):
            self.gen_import(node)
        elif isinstance(node, ClassDecl):
            self.gen_class(node)
        elif isinstance(node, Block):
            for s in node.stmts:
                self.gen_stmt(s)
        elif isinstance(node, Assign):
            if isinstance(node.value, Lambda) and isinstance(node.value.body, Block) and isinstance(node.target, Ident):
                self._register_funcref_var(node.target.name)
            val = self.gen_expr(node.value)
            target = self.gen_expr(node.target)
            self.emit(f"let {target} = {val}")
        elif isinstance(node, AugAssign):
            target = self.gen_expr(node.target)
            val = self.gen_expr(node.value)
            self.emit(f"let {target} {node.op} {val}")
        else:
            raise CodegenError(f"Unknown statement node: {type(node).__name__}")

    def _is_call_expr(self, node: Node) -> bool:
        return isinstance(node, (Call, Await))

    def gen_var_decl(self, node: VarDecl):
        if node.name in self._consts:
            raise CodegenError(f"Cannot reassign const '{node.name}'")
        if node.kind == "const":
            self._consts.add(node.name)

        is_script_scope = self.function_depth == 0
        if is_script_scope:
            self.script_vars.add(node.name)

        scope = "l" if not is_script_scope else "s"
        if isinstance(node.value, Lambda) and isinstance(node.value.body, Block):
            self._register_funcref_var(node.name)
        val = self.gen_expr(node.value) if node.value else "0"
        self.emit(f"let {scope}:{self._cap_funcref_name(node.name)} = {val}")

    def gen_fn_decl(self, node: FnDecl):
        params = [p for p, _ in node.params]
        param_str = ", ".join(params)
        scope_fn = "s:" if self.function_depth == 0 else ""

        self.enter_scope("fn", params)
        try:
            if node.is_async:
                self._gen_async_fn(node, scope_fn, param_str)
            else:
                self.emit(f"function! {scope_fn}{node.name}({param_str})")
                self.indent_level += 1
                for s in node.body.stmts:
                    self.gen_stmt(s)
                self.indent_level -= 1
                self.emit(f"endfunction")
        finally:
            self.leave_scope()

    def _gen_async_fn(self, node: FnDecl, scope_fn: str, params: str):
        """
        async fn wraps body in job_start with callbacks.
        Awaited expressions become sequential job_start chains.
        """
        self.emit(f"function! {scope_fn}{node.name}({params})")
        self.indent_level += 1
        self.emit(f'" async function — uses job_start internally')
        # Rewrite body: find Await nodes and wrap in job chains
        self._gen_async_body(node.body.stmts)
        self.indent_level -= 1
        self.emit(f"endfunction")

    def _gen_async_body(self, stmts: List[Node]):
        """Emit statements; Await(Call) becomes a job_start."""
        for stmt in stmts:
            if isinstance(stmt, VarDecl) and isinstance(stmt.value, Await):
                self._gen_job_await(stmt)
            elif isinstance(stmt, ExprStmt) and isinstance(stmt.expr, Await):
                self._gen_job_fire_and_forget(stmt.expr)
            else:
                self.gen_stmt(stmt)

    def _gen_job_await(self, node: VarDecl):
        """let result = await job("cmd") → job_start with stdout capture"""
        jid = self._job_counter
        self._job_counter += 1
        scope = "l" if self.indent_level > 0 else "s"
        await_expr = node.value  # Await node
        cmd = self.gen_expr(await_expr.expr)
        self.emit(
            f'let {scope}:{node.name} = #{{"stdout": [], "stderr": [], "exit": -1}}'
        )
        self.emit(f"let l:__job_{jid}_result = {scope}:{node.name}")
        self.emit(f"let l:__job_{jid}_done = 0")
        self.emit(f"function! s:__job_{jid}_out(ch, data) closure")
        self.enter_scope("fn", ["ch", "data"])
        self.indent_level += 1
        self.emit(f"call add(l:__job_{jid}_result.stdout, a:data)")
        self.indent_level -= 1
        self.leave_scope()
        self.emit(f"endfunction")

        self.emit(f"function! s:__job_{jid}_exit(job, code) closure")
        self.enter_scope("fn", ["job", "code"])
        self.indent_level += 1
        self.emit(f"let l:__job_{jid}_result.exit = a:code")
        self.emit(f"let l:__job_{jid}_done = 1")
        self.indent_level -= 1
        self.leave_scope()
        self.emit(f"endfunction")
        self.emit(
            f'call job_start({cmd}, #{{"out_cb": function("s:__job_{jid}_out"), "exit_cb": function("s:__job_{jid}_exit")}})'
        )
        self.emit(f"while !l:__job_{jid}_done")
        self.indent_level += 1
        self.emit(f"sleep 10m")
        self.indent_level -= 1
        self.emit(f"endwhile")

    def _gen_job_fire_and_forget(self, node: Await):
        cmd = self.gen_expr(node.expr)
        self.emit(f"call job_start({cmd})")

    def gen_return(self, node: Return):
        if node.value:
            self.emit(f"return {self.gen_expr(node.value)}")
        else:
            self.emit("return")

    def gen_if(self, node: If):
        self.emit(f"if {self.gen_expr(node.condition)}")
        self.indent_level += 1
        for s in node.then.stmts:
            self.gen_stmt(s)
        self.indent_level -= 1
        for ei_cond, ei_body in node.elseifs:
            self.emit(f"elseif {self.gen_expr(ei_cond)}")
            self.indent_level += 1
            for s in ei_body.stmts:
                self.gen_stmt(s)
            self.indent_level -= 1
        if node.else_:
            self.emit("else")
            self.indent_level += 1
            for s in node.else_.stmts:
                self.gen_stmt(s)
            self.indent_level -= 1
        self.emit("endif")

    def gen_for(self, node: For):
        scope = "l" if self.function_depth > 0 else "s"
        self.emit(f"for {scope}:{node.var} in {self.gen_expr(node.iterable)}")
        self.indent_level += 1
        for s in node.body.stmts:
            self.gen_stmt(s)
        self.indent_level -= 1
        self.emit("endfor")

    def gen_while(self, node: While):
        self.emit(f"while {self.gen_expr(node.condition)}")
        self.indent_level += 1
        for s in node.body.stmts:
            self.gen_stmt(s)
        self.indent_level -= 1
        self.emit("endwhile")

    def gen_import(self, node: Import):
        self.emit(f"source {node.source}.vim")
        for name in node.names:
            self._imported_names.add(name)

    def gen_class(self, node: ClassDecl):
        self._classes.add(node.name)
        ctor_name = f"s:{node.name}_new"
        self.emit(f'" Class: {node.name}')
        self.emit(f"function! {ctor_name}(...)")
        self.enter_scope("fn", ["..."])
        self.indent_level += 1
        self.emit(f"let l:self = {{}}")
        for field in node.fields:
            val = self.gen_expr(field.value) if field.value else "0"
            self.emit(f"let l:self.{field.name} = {val}")
        for method in node.methods:
            params = [p for p, _ in method.params]
            param_str = ", ".join(params)
            self.emit(f"function! l:self.{method.name}({param_str}) closure")
            self.enter_scope("fn", params)
            self.indent_level += 1
            for s in method.body.stmts:
                self.gen_stmt(s)
            self.indent_level -= 1
            self.leave_scope()
            self.emit(f"endfunction")
        self.emit(f"return l:self")
        self.indent_level -= 1
        self.leave_scope()
        self.emit(f"endfunction")

    # ── Expressions ───────────────────────────────────────────────────────────

    def gen_expr(self, node: Node) -> str:
        if isinstance(node, NumberLit):
            return node.value
        if isinstance(node, StringLit):
            escaped = node.value.replace("'", "''")
            return f"'{escaped}'"
        if isinstance(node, BoolLit):
            return "1" if node.value else "0"
        if isinstance(node, NullLit):
            return "v:null"
        if isinstance(node, Ident):
            return self._resolve_ident(node.name)
        if isinstance(node, ListLit):
            elems = ", ".join(self.gen_expr(e) for e in node.elements)
            return f"[{elems}]"
        if isinstance(node, DictLit):
            pairs = ", ".join(
                (
                    f"'{k.value}': {self.gen_expr(v)}"
                    if isinstance(k, StringLit)
                    else f"{self.gen_expr(k)}: {self.gen_expr(v)}"
                )
                for k, v in node.pairs
            )
            return f"{{{pairs}}}"
        if isinstance(node, BinOp):
            return self.gen_binop(node)
        if isinstance(node, UnaryOp):
            return self.gen_unary(node)
        if isinstance(node, Assign):
            return f"({self.gen_expr(node.target)} = {self.gen_expr(node.value)})"
        if isinstance(node, AugAssign):
            return f"{self.gen_expr(node.target)} {node.op} {self.gen_expr(node.value)}"
        if isinstance(node, Attr):
            return f"{self.gen_expr(node.obj)}.{node.attr}"
        if isinstance(node, Index):
            return f"{self.gen_expr(node.obj)}[{self.gen_expr(node.index)}]"
        if isinstance(node, Call):
            return self.gen_call(node)
        if isinstance(node, Lambda):
            return self.gen_lambda(node)
        if isinstance(node, Await):
            return self.gen_expr(node.expr)
        if isinstance(node, Pipeline):
            return self.gen_pipeline(node)
        if isinstance(node, New):
            args = ", ".join(self.gen_expr(a) for a in node.args)
            return f"s:{node.class_name}_new({args})"
        raise CodegenError(f"Unknown expr node: {type(node).__name__}")

    def _resolve_ident(self, name: str) -> str:
        if name == "self":
            return "l:self"
        # Built-in Vim variables
        if name.startswith("g:") or name.startswith("v:") or name.startswith("a:"):
            return name

        # Imported names are global (no scope prefix)
        if name in self._imported_names:
            return name

        # Check current scope stack (arguments)
        for scope in reversed(self.scope_stack):
            if name in scope["params"]:
                if scope["kind"] == "fn":
                    return f"a:{name}"
                # Lambda params have no prefix in Vim script lambda body
                return name

        # Check if it's a known script-level variable or class name
        if name in self.script_vars or name in self._classes:
            return f"s:{self._cap_funcref_name(name)}"

        # Local scope inside function
        if self.function_depth > 0:
            return f"l:{self._cap_funcref_name(name)}"
        return f"s:{self._cap_funcref_name(name)}"

    def gen_binop(self, node: BinOp) -> str:
        l = self.gen_expr(node.left)
        r = self.gen_expr(node.right)
        op_map = {
            "&&": "&&",
            "||": "||",
            "==": "==",
            "!=": "!=",
            "<": "<",
            ">": ">",
            "<=": "<=",
            ">=": ">=",
            "+": "+",
            "-": "-",
            "*": "*",
            "/": "/",
            "%": "%",
            "..": " .. ",
        }
        op = op_map.get(node.op, node.op)
        return f"({l} {op} {r})"

    def gen_unary(self, node: UnaryOp) -> str:
        operand = self.gen_expr(node.operand)
        if node.op == "!":
            return f"!({operand})"
        if node.op == "-":
            return f"-({operand})"
        return f"{node.op}{operand}"

    def gen_call(self, node: Call, toplevel_helper: bool = True) -> str:
        callee = self.gen_expr(node.callee)
        args = ", ".join(self.gen_expr(a) for a in node.args)

        # Built-in VimMo helpers (only when called directly by name at top level)
        if isinstance(node.callee, Ident) and toplevel_helper:
            name = node.callee.name
            if name == "job":
                return args
            if name == "autocmd":
                return self._gen_autocmd_call(node.args)
            if name == "command":
                return self._gen_command_call(node.args)
            if name == "map" and len(node.args) == 3:
                # Distinguish vim-map helper (3 args: mode, lhs, cb) from list map
                # Heuristic: first arg is mode string like "n","i","v"
                first = node.args[0]
                if isinstance(first, StringLit) and first.value in (
                    "n",
                    "i",
                    "v",
                    "x",
                    "o",
                    "c",
                    "t",
                ):
                    return self._gen_map_call(node.args)

        # Method call via Attr
        if isinstance(node.callee, Attr):
            obj = self.gen_expr(node.callee.obj)
            method = node.callee.attr
            builtin = self._gen_builtin_method(obj, method, node.args)
            if builtin:
                return builtin
            return f"{obj}.{method}({args})"

        return f"{callee}({args})"

    def _gen_builtin_method(
        self, obj: str, method: str, args: List[Node]
    ) -> Optional[str]:
        mapped = {
            "map": lambda: f"map({obj}, {self.gen_expr(args[0])})",
            "filter": lambda: f"filter({obj}, {self.gen_expr(args[0])})",
            "push": lambda: f"add({obj}, {self.gen_expr(args[0])})",
            "pop": lambda: f"remove({obj}, -1)",
            "len": lambda: f"len({obj})",
            "join": lambda: f"join({obj}, {self.gen_expr(args[0]) if args else chr(39) + chr(39)})",
            "split": lambda: f"split({obj}, {self.gen_expr(args[0]) if args else chr(39) + chr(39)})",
            "keys": lambda: f"keys({obj})",
            "values": lambda: f"values({obj})",
            "has": lambda: f"has_key({obj}, {self.gen_expr(args[0])})",
        }
        if method in mapped:
            return mapped[method]()
        return None

    def gen_lambda(self, node: Lambda) -> str:
        params = ", ".join(node.params)
        if isinstance(node.body, Block):
            fname = f"s:__lambda_{self._lambda_counter}"
            self._lambda_counter += 1
            # Emit inline at current indentation so nested functions can use 'closure'
            # to capture l: variables from the enclosing function (Vim 8+ feature).
            is_nested = self.function_depth > 0
            closure_attr = " closure" if is_nested else ""
            self.emit(f"function! {fname}({params}){closure_attr}")
            self.enter_scope("fn", node.params)
            self.indent_level += 1
            for s in node.body.stmts:
                self.gen_stmt(s)
            self.indent_level -= 1
            self.leave_scope()
            self.emit("endfunction")
            self.emit("")
            return f'function("{fname}")'
        else:
            self.enter_scope("lambda", node.params)
            body = self.gen_expr(node.body)
            self.leave_scope()
            if params:
                # In lambdas, params are accessed without scope prefix
                return f"{{{params} -> {body}}}"
            else:
                return f"{{-> {body}}}"

    def _emit_lambda_fn(
        self, node: Lambda, params_override: Optional[List[str]] = None
    ) -> str:
        """Emit a lambda as a named function inline at current indentation and return its name."""
        params = params_override or node.params
        fname = f"s:__lambda_{self._lambda_counter}"
        self._lambda_counter += 1
        param_str = ", ".join(params)
        is_nested = self.function_depth > 0
        closure_attr = " closure" if is_nested else ""

        self.emit(f"function! {fname}({param_str}){closure_attr}")
        self.enter_scope("fn", params)
        self.indent_level += 1
        if isinstance(node.body, Block):
            for s in node.body.stmts:
                self.gen_stmt(s)
        else:
            self.emit(f"return {self.gen_expr(node.body)}")
        self.indent_level -= 1
        self.leave_scope()
        self.emit("endfunction")
        self.emit("")
        return fname

    def gen_pipeline(self, node: Pipeline) -> str:
        from ast_nodes import Call, Ident, Attr

        left = self.gen_expr(node.left)
        right = node.right
        if isinstance(right, Call) and isinstance(right.callee, Ident):
            name = right.callee.name
            mapped = {
                "filter": "filter",
                "map": "map",
            }
            if name in mapped:
                vim_fn = mapped[name]
                if right.args:
                    cb = self.gen_expr(right.args[0])
                    return f"{vim_fn}({left}, {cb})"
                return f"{vim_fn}({left})"
        right_str = self.gen_expr(right)
        return f"call({right_str}, [{left}])"

    def _gen_autocmd_call(self, args: List[Node]) -> str:
        if len(args) < 3:
            raise CodegenError("autocmd() requires 3 args: event, pattern, callback")
        event = self.gen_expr(args[0]).strip("'")
        pattern = self.gen_expr(args[1]).strip("'")
        cb_node = args[2]
        if isinstance(cb_node, Lambda):
            fname = self._emit_lambda_fn(cb_node)
            cb_call = f"{fname}()"
        else:
            cb_call = f"{self.gen_expr(cb_node)}()"
        self.emit(f"augroup VimMo_{event}")
        self.indent_level += 1
        self.emit(f"autocmd!")
        self.emit(f"autocmd {event} {pattern} call {cb_call}")
        self.indent_level -= 1
        self.emit("augroup END")
        return ""

    def _gen_command_call(self, args: List[Node]) -> str:
        if len(args) < 2:
            raise CodegenError("command() requires 2 args: name, callback")
        name = self.gen_expr(args[0]).strip("'")
        cb_node = args[1]
        if isinstance(cb_node, Lambda):
            fname = self._emit_lambda_fn(cb_node, ["args"])
            self.emit(f"command! -nargs=* {name} call {fname}(<q-args>)")
        else:
            cb = self.gen_expr(cb_node)
            self.emit(f"command! -nargs=* {name} call {cb}(<q-args>)")
        return ""

    def _gen_map_call(self, args: List[Node]) -> str:
        if len(args) < 3:
            raise CodegenError("map() requires 3 args: mode, lhs, callback")
        mode = self.gen_expr(args[0]).strip("'")
        lhs = self.gen_expr(args[1]).strip("'")
        cb_node = args[2]
        if isinstance(cb_node, Lambda):
            fname = self._emit_lambda_fn(cb_node)
            self.emit(f"{mode}noremap <silent> {lhs} :<C-u>call {fname}()<CR>")
        else:
            cb = self.gen_expr(cb_node)
            self.emit(f"{mode}noremap <silent> {lhs} :<C-u>call {cb}()<CR>")
        return ""
