" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

let s:x = 10

let s:y = 'hello'

let s:myList = [1, 2, 3]

let s:myDict = {'a': 1, 'b': 2}

echo s:x

echo s:y
