" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

let s:x = 10

if (s:x > 5)
  echo 'big'
else
  echo 'small'
endif

let s:i = 0

while (s:i < 3)
  echo s:i
  let s:i += 1
endwhile

let s:items = [1, 2, 3]

for s:item in s:items
  echo s:item
endfor
