" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

let s:double = {x -> (x * 2)}

echo s:double(10)

" Class: Counter
function! s:Counter_new(...)
  let l:self = {}
  let l:self.count = 0
  function! l:self.inc() closure
    let l:self.count += 1
  endfunction
  return l:self
endfunction

let s:c = s:Counter_new()

call s:c.inc()

echo s:c.count
