" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

function! s:fetchData()
  " async function — uses job_start internally
  let l:result = #{"stdout": [], "stderr": [], "exit": -1}
  let l:__job_0_result = l:result
  let l:__job_0_done = 0
  function! s:__job_0_out(ch, data) closure
    call add(l:__job_0_result.stdout, a:data)
  endfunction
  function! s:__job_0_exit(job, code) closure
    let l:__job_0_result.exit = a:code
    let l:__job_0_done = 1
  endfunction
  call job_start('echo ''hello''', #{"out_cb": function("s:__job_0_out"), "exit_cb": function("s:__job_0_exit")})
  while !l:__job_0_done
    sleep 10m
  endwhile
  echo l:result
endfunction

function! s:main()
  call l:fetchData()
endfunction
