" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

source ./06_utils.vim

let s:sum = VimmoAdd(3, 4)

echo s:sum

let s:msg = VimmoGreet('VimMo')

echo s:msg
