" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

let s:nums = [1, 2, 3, 4, 5]

let s:result = map(filter(s:nums, {x -> (x > 2)}), {x -> (x * 10)})

echo s:result
