" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

let s:arr = [1, 2, 3]

call add(s:arr, 4)

echo len(s:arr)

echo remove(s:arr, -1)

let s:filtered = filter(s:arr, {x -> (x > 2)})

echo s:filtered

let s:mapped = map(s:arr, {x -> (x * 2)})

echo s:mapped

let s:d = {'a': 1, 'b': 2}

echo keys(s:d)

echo values(s:d)

echo has_key(s:d, 'a')
