" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

function! s:makeCounter()
  let l:count = 0
function! s:__lambda_0()
  let l:count = (l:count + 1)
  echo l:count
endfunction

  let l:inc = function("s:__lambda_0")
  call l:inc()
  call l:inc()
endfunction

call s:makeCounter()
