" Generated by VimMo transpiler
" https://github.com/vimmo-lang/vimmo

scriptencoding utf-8

" Class: Counter
function! s:Counter_new(...)
  let l:self = {}
  let l:self.count = 0
  function! l:self.increment() closure
    let l:self.count = (l:self.count + 1)
  endfunction
  function! l:self.get() closure
    return l:self.count
  endfunction
  return l:self
endfunction

let s:c = s:Counter_new()

call s:c.increment()

echo s:c.get()
